### ISSUE TITLE
make sure to call FacebookSdk.sdkInitialize() first.

### ISSUE THREAD

**Issue by inTao** [Innim/flutter_login_facebook#87]
Error registering plugin flutter_login_facebook, ru.innim.flutter_login_facebook.FlutterLoginFacebookPlugin
                                                                                                    The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
                                                                                                    	at com.facebook.internal.Validate.sdkInitialized(Validate.kt:129)
                                                                                                    	at com.facebook.login.LoginManager.<init>(LoginManager.kt:1398)
                                                                                                    	at com.facebook.login.LoginManager$Companion.getInstance(LoginManager.kt:1319)
                                                                                                    	at com.facebook.login.LoginManager.getInstance(Unknown Source:2)
                                                                                                    	at ru.innim.flutter_login_facebook.FlutterLoginFacebookPlugin._setActivity(FlutterLoginFacebookPlugin.java:70)
                                                                                                    	at ru.innim.flutter_login_facebook.FlutterLoginFacebookPlugin.onAttachedToActivity(FlutterLoginFacebookPlugin.java:39)
                                                                                                    	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:154)
                                                                                                    	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:111)
                                                                                                    	at com.duixivideo.app.MainActivity.configureFlutterEngine(MainActivity.kt:14)
                                                                                                    	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:200)
                                                                                                    	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
                                                                                                    	at com.duixivideo.app.MainActivity.onCreate(MainActivity.kt:18)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8093)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8067)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3493)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3692)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2142)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:236)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7864)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by ChenLianghui** [comment]
I have the same problem. Have you solved it？
